spring:
    application:
        name: graindepot-gateway-zuul

server:
    port: 8001 #启动端口

zuul:
  sensitiveHeaders:
  #add-host-header: true
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 10000
    connect-timeout-millis: 10000
  routes:
    user:
        path: /graindepot-user/**
        serviceId: graindepot-user
    inout:
        path: /graindepot-inout/**
        serviceId: graindepot-inout
    bussiness:
        path: /graindepot-bussiness/**
        serviceId: graindepot-bussiness
    upload:
        path: /upload/**
        serviceId: grain-upload

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
security:
    user:
        name: admin
        password: admin
        role: USER